### ISSUE TITLE
[Feature: Ranking ability] Add ranking model to refine the order of data after embedding recall

### ISSUE THREAD

**Issue by isHuangXin** [codefuse-ai/ModelCache#42]
This issue is created to better track my PRs for Todo List [Rank ability]

## Background
Efficiently retrieving relevant results from large-scale datasets plays a crucial role in software development and Q&A tasks, including code recommendation and vulnerability code clone discovery. Existing search approaches suffer the difficulty of being scaled up, while maintaining the effectiveness of retrieved results. 

## Prototype
In this paper, we propose a two-stage search framework to address these limitations and achieve both effectiveness and efficiency in the search Scenario. We will add ranking model to refine the order of data after embedding recall.

<img width="1250" alt="Screenshot 2024-05-28 at 10 37 53" src="https://github.com/codefuse-ai/ModelCache/assets/57054352/b561d7e3-1fcb-400c-bfc1-088f96f4ad08">

## Task

- [ ] Add ranking model to refine the order of data after embedding recall.

**Comment by peng3307165** [comment]
Due to certain reasons, we have closed this issue, and the ranking model will be implemented in a future iteration.
