### ISSUE TITLE
[编程挑战季] ModelCache文档编写

### ISSUE THREAD

**Issue by peng3307165** [codefuse-ai/ModelCache#50]
1. 问题简述
代码转文档（中文和英文），涵盖Getting Started、Feature、configure、Release Note等文档module，可以参考内部使用文档，使用mardown风格。
2. 期望产出
一个PR即可，同时上传中英文两个版本到https://github.com/codefuse-ai/codefuse-ai.github.io 仓库。
3. 能力要求
熟悉python代码，良好的文档编写能力

**Comment by amber-moe** [comment]
Please assign this to me. I happen to be a technical writer.
