### ISSUE TITLE
[编程挑战季] Docker File For ModelCache

### ISSUE THREAD

**Issue by peng3307165** [codefuse-ai/ModelCache#52]
1. 问题简述：
为方便兼容不同的运行平台（Mac、windows、linux），以及部分SDK安装依赖的网络问题，提供对应的Docker File，已经对应的Docker镜像，方便开源用户测试使用。
2. 期望产出：
完整的Docker File文件。
3. 能力要求：
了解Docker相关知识

**Comment by flycoding0817** [comment]
assign this issue to me

**Comment by camaze** [comment]
If the previous student is too busy with his work and doesn't have time to handle this issue, could you please assign this issue to me?

**Comment by peng3307165** [comment]
> If the previous student is too busy with his work and doesn't have time to handle this issue, could you please assign this issue to me?

We are pleased that you have taken on this task. If you have any questions or need assistance, please feel free to contact us.
