### ISSUE TITLE
[编程挑战季] Fast API 接口能力

### ISSUE THREAD

**Issue by peng3307165** [codefuse-ai/ModelCache#53]
1. 问题简述：
Web服务框架转换，当前ModelCache提供的是flask web服务，希望将其转换为更通用的Fast API服务框架
2. 期望产出：
flask4modelcache.py、flask4modelcache_demo.py、flask4multicache.py、flask4multicache_demo.py
4个文件转换为Fast API服务，可以在测试example上运行。
3. 能力要求：
了解Fast API服务框架

**Comment by charleschile** [comment]
Please assign this to me, I will change the frame to Fast API.

**Comment by charleschile** [comment]
PR #58
