### ISSUE TITLE
[编程挑战季] More Embedding Generator

### ISSUE THREAD

**Issue by peng3307165** [codefuse-ai/ModelCache#54]
1. 问题简述
作为ModelCache核心模块，Embedding能力对Cache的效果至关重要，根据业界前沿方向，增加更好的Embedding Generator，包括但不限于Embedding模型、Embedding加速推理技术。
2. 期望产出
增加新的embedding模型，在modelcache/embedding/目录下，实现新的embedding推理模块。
3. 能力要求
了解embedding模型以及embedding推理技术

**Comment by charleschile** [comment]
Please assign this to me, I will try to use bge generator and other open-source models.
