### ISSUE TITLE
[编程挑战季] ModelCache检索的Reranker 能力

### ISSUE THREAD

**Issue by peng3307165** [codefuse-ai/ModelCache#55]
1. 问题简述
通过向量数据库检索embedding作为初次召回，仅通过L2或者cosine计算相似度，无法保障召回的query和用户的query完全匹配，希望完善Reranker能力，使用reranker模型进行二次排序，增加Cache的命中的准确性。
2. 期望产出
在ModelCache的 adapter_query 模块增加Reranker模块，实现二次排序能力。
3. 能力要求
熟悉python代码，了解prompt工程。

**Comment by charleschile** [comment]
Please assign this to me, I will try to use bge reranker and other open-source models.

**Comment by DreamCyc** [comment]
Oh, I'm late. If the previous student is too busy to handle it, I can assist in completing it. Additionally, the BGE embedding model is quite effective in terms of representation capability.

**Comment by charleschile** [comment]
#63
