### ISSUE TITLE
[编程挑战季]为ModelCache提供多种存储方案能力

### ISSUE THREAD

**Issue by peng3307165** [codefuse-ai/ModelCache#57]
1. 问题简述
做为开源项目，我们希望支持更多的存储能力，包括 scalar database和vector database，包括但不限于：Chroma、ElasticSearch等。
2. 期望产出
在modelcache/scalar_data 和 modelcache/vector_data 目录下增加对应的数据存储方案。
3. 能力要求
熟悉python代码，了解基础数据库知识。

**Comment by powerli2002** [comment]
Please assign this to me, I have previously contributed database-related content to this repository, and I will continue to try to improve it.

**Comment by peng3307165** [comment]
> Please assign this to me, I have previously contributed database-related content to this repository, and I will continue to try to improve it.

We are pleased that you have taken on this task. If you have any questions or need assistance, please feel free to contact us.
